### ISSUE TITLE
Why IssueRules.yml doestn't work?

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [damccorm/tag-ur-it#12]
## Required Information

I have [IssueRules.yml](https://github.com/NETMouse-projects/ABCNET/blob/master/IssueRules.yml) and [issues.yml](https://github.com/NETMouse-projects/ABCNET/blob/master/.github/workflows/issues.yml). Why when I create new issue within the second `.yml` one an error occurs:
```
github-actions/label

.github#L1
TypeError: Cannot read property 'length' of undefined
```

**Question, Bug, or Feature?**  
*Type*: Question

Should this get assigned to @damccorm?
**Assign to damccorm**: yes

**Comment by damccorm** [comment]
I think this was an issue with not having null checks - it should be fixed, let me know if you're still having issues

**Comment by EmilyGraceSeville7cf** [comment]
I'm still having this issue. I'm waiting when this problem would be fixed or when somebody tell me any workaround.

**Comment by damccorm** [comment]
@Alvin-Seville it looks like it worked in a run for an issue I just created - https://github.com/NETMouse-projects/ABCNET/runs/411256268?check_suite_focus=true

**Comment by EmilyGraceSeville7cf** [comment]
Yes, now it works...
