### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [damccorm/tag-ur-it#16]
I want to help you to create the documentation for this `GitHub Action`. I use it and I want my organization members to understand it quickly. How do you recommend me to write it? In what program?

**Comment by damccorm** [comment]
Hm, I don't have much I can recommend here. I've mostly just added docs to the README, but I agree more would be better - if I were to do it, I'd probably start a docs folder and just add `.md` files there with docs.

**Comment by EmilyGraceSeville7cf** [comment]
Closed as being inactive for a long time. Please reopen if it's required.
