### ISSUE TITLE
Bot accidentally removes added labels 

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [damccorm/tag-ur-it#18]
## Required Information

Bot accidentally removes added labels 

**Question, Bug, or Feature?**  
*Type*: Bug

Should this get assigned to @damccorm?
**Assign to damccorm**: yes

## Issue Description

[Issue](https://github.com/NETMouse-projects/ABCNET/issues/59) example.

**Comment by damccorm** [comment]
@Alvin-Seville any chance you can point me to an issue where it does this? I'm a little surprised by this behavior because as far as I know we don't have any logic anywhere to remove labels.

**Comment by EmilyGraceSeville7cf** [comment]
I was really surprised too when I [saw](https://github.com/NETMouse-projects/ABCNET/issues/59) it. I think that it has happed because I used multiple rules [here](https://github.com/NETMouse-projects/ABCNET).

![image](https://user-images.githubusercontent.com/42812113/73585812-19742480-44b6-11ea-8afc-b08ba76dc3cf.png)

**Comment by EmilyGraceSeville7cf** [comment]
This problem still [exists](https://github.com/NETMouse-projects/ABCNET/issues/68).

**Comment by EmilyGraceSeville7cf** [comment]
Closed as being inactive for a long time. Please reopen if it's required.
