### ISSUE TITLE
Support for checkboxes

### ISSUE THREAD

**Issue by Stanzilla** [damccorm/tag-ur-it#21]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Feature

Should this get assigned to @damccorm?
**Assign to damccorm**: yes

## Issue Description

Would love to way to act on the status of a checkbox being checked or not

**Comment by parthpandyappp** [comment]
Type: Enhance

**Comment by damccorm** [comment]
Hey, sorry this slipped through the cracks. This is actually doable today! Here's an example of where we're doing this with apache/beam - https://github.com/apache/beam/blob/ab5992940c1e3c1d004cfd40d8a087e1d6436f5e/.github/issue-rules.yml#L51

Basically, you can use `- [ ] Content` to detect an unchecked box and `- [x] Content` to detect a checked box.
